package com.wuhai.demo.lotteryticketkotlin.model.dao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.wuhai.demo.lotteryticketkotlin.model.bean.Lottery;
import com.wuhai.demo.lotteryticketkotlin.model.bean.LotteryRecord;

import com.wuhai.demo.lotteryticketkotlin.model.dao.LotteryDao;
import com.wuhai.demo.lotteryticketkotlin.model.dao.LotteryRecordDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig lotteryDaoConfig;
    private final DaoConfig lotteryRecordDaoConfig;

    private final LotteryDao lotteryDao;
    private final LotteryRecordDao lotteryRecordDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        lotteryDaoConfig = daoConfigMap.get(LotteryDao.class).clone();
        lotteryDaoConfig.initIdentityScope(type);

        lotteryRecordDaoConfig = daoConfigMap.get(LotteryRecordDao.class).clone();
        lotteryRecordDaoConfig.initIdentityScope(type);

        lotteryDao = new LotteryDao(lotteryDaoConfig, this);
        lotteryRecordDao = new LotteryRecordDao(lotteryRecordDaoConfig, this);

        registerDao(Lottery.class, lotteryDao);
        registerDao(LotteryRecord.class, lotteryRecordDao);
    }
    
    public void clear() {
        lotteryDaoConfig.clearIdentityScope();
        lotteryRecordDaoConfig.clearIdentityScope();
    }

    public LotteryDao getLotteryDao() {
        return lotteryDao;
    }

    public LotteryRecordDao getLotteryRecordDao() {
        return lotteryRecordDao;
    }

}
