package com.wuhai.lotteryticket.model.dao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.wuhai.lotteryticket.model.bean.Lottery;

import com.wuhai.lotteryticket.model.dao.LotteryDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig lotteryDaoConfig;

    private final LotteryDao lotteryDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        lotteryDaoConfig = daoConfigMap.get(LotteryDao.class).clone();
        lotteryDaoConfig.initIdentityScope(type);

        lotteryDao = new LotteryDao(lotteryDaoConfig, this);

        registerDao(Lottery.class, lotteryDao);
    }
    
    public void clear() {
        lotteryDaoConfig.clearIdentityScope();
    }

    public LotteryDao getLotteryDao() {
        return lotteryDao;
    }

}
